#!/usr/bin/env bash
# nx -t && service nginx restart || echo "Config test or restart failed."Fixes server bug
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
nginx -t && service nginx restart || echo "Config test or restart failed."
