#!/usr/bin/env bash
#Configures HAProxy to be able to accept requests on port tcp/80 and redirect them to the web servers
sudo apt update -y
sudo apt install haproxy -y
config=\
"backend my_servers
    server 6005-web-01 35.172.201.241:80 check
    server 6005-web-02 52.207.229.0:80 check
frontend haproxy_inbound
        bind *:80
        default_backend my_servers
        mode http
"

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "$config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
